name: Deployment & publish source
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  Deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main' &&
      !contains(github.event.workflow_run.head_commit.message, '#skip') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run:
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN
          }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  PublishSource:
    if: ${{ github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main' &&
      !contains(github.event.workflow_run.head_commit.message, '#skip') }}

    runs-on: ubuntu-latest
    needs: [Deploy]

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.email "example@gmail.com"
          git config --global user.name "John Doe"

      - name: Clone public repo
        run: |
          git clone https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/${{ secrets.PUBLIC_REPO }} public_repo

      - name: Sync source into public repo
        run: |
          rsync -av --delete \
            --exclude '.git' \
            --exclude 'src/data' \
            --exclude 'templateData' \
            --exclude 'CHANGELOG.md' \
            --exclude '.github/workflows/deploy_publish.yml' \
            --exclude '.github/workflows/release.yml' \
            --exclude 'release_template.yml' \
            --exclude 'ToDo.md' \
            --exclude '.vercelignore' \
            ./ public_repo/

      - name: Replace private data with template data
        run: |
          rm -rf public_repo/src/data
          mkdir -p public_repo/src/data
          cp -r templateData/* public_repo/src/data/

      - name: Add release workflow
        run: |
          mkdir -p public_repo/.github/workflows
          cp release_template.yml public_repo/.github/workflows/release.yml

      - name: Commit changes
        run: |
          cd public_repo
          git add -A
          git status
          git commit -m "sync: public repository update" || echo "No changes"

      - name: Push changes
        run: |
          cd public_repo
          git push origin main
