name: Deployment & publish source
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed
jobs:
  Deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main' &&
      !contains(github.event.workflow_run.head_commit.message, '#skip') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN
          }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  PublishSource:
    if: ${{ github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main' &&
      !contains(github.event.workflow_run.head_commit.message, '#skip') }}
    runs-on: ubuntu-latest
    needs: [ Deploy ]

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install git-filter-repo
        run: pip install git-filter-repo

      - name: Clone repo
        run: |
          git clone https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/${{ github.repository }} public_repo

      - name: Filter repo
        run: |
          cd public_repo
          git filter-repo \
          --invert-paths \
          --path src/data/ \
          --path templateData \
          --path CHANGELOG.md \
          --path .github/workflows/deploy_publish.yml \
          --path .vercelignore

      - name: Copy template data
        run: |
          cd public_repo

          mkdir -p src/data
          cp -r ../templateData/* src/data/
          cp -r ../release_template.yml .github/workflows/release.yml
      - name: Commit template data
        run: |
          cd public_repo

          git config user.email "jkaart@gmail.com"
          git config user.name "Jani Kaartinen"

          git add -A
          git commit -m "Public version (data replaced with examples)" || echo "No changes"
      - name: Push to public repo
        run: |
          cd public_repo
          git remote add public https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/${{ secrets.PUBLIC_REPO }}

          git ls-tree -r HEAD --name-only | grep data || true
          git log -1
          git diff HEAD~1 || true

          git push -f public HEAD:main
