name: Publish public repo

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install git-filter-repo
        run: pip install git-filter-repo
      - name: Clone repo
        run: |
          git clone --mirror https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/${{ github.repository }} public_repo 
      - name: Filter repo
        run: |
          cd public_repo
          git filter-repo \
          --invert-paths \
          --path src/data/ \
          --path .github/workflows/publish-source.yml
      - name: Push to public repo
        run: |
          cd public_repo

          git remote add public https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/jkaart/nextjs-cv.git

          git push -f public HEAD:main